update to align with Features Part 6
interactive-instruments/ldproxy pull request #1244
Opened 2024-08-03 09:49 UTC by cportele

### Pull request checklist

-   [ ] Added/updated unit tests
-   [x] Updated documentation
-   [x] All checks are passing

### Changes introduced by this PR

deprecate support for `skipGeometry`, include spatial properties in `properties`, add support for `exclude-properties`, add conformance class URIs

closes #1240

depends on https://github.com/interactive-instruments/xtraplatform-spatial/pull/279

2024-08-03 09:58 UTC, azahnen commented
<!--woodpeckerci-plugin-surge-preview-->
Deploying preview to https://interactive-instruments-ldproxy-pr-1244.surge.sh

2024-08-16 07:11 UTC, azahnen requested changes
This works mostly as expected, but I spotted some potential issues:

- `exclude-properties` will always exclude the geometry, even if it is not part of the list. I guess that is not intentional?
- The OpenAPI schema for the parameter was not adjusted to contain the geometry.
- This is not a new issue, but the parameter values are not validated. That might not have to be implemented right now, but before we move this to mature/stable.

2024-08-20 17:47 UTC, cportele commented
@azahnen 

The issues should be fixed.

The parameter values were validated, but the schema validation did not work properly for query parameters with array values, most values were accepted.

2024-08-21 11:59 UTC, azahnen approved these changes

2024-08-21 12:39 UTC, merged